### ISSUE TITLE
Do not force the frame around the license

### ISSUE THREAD

**Issue by samoht** [dbuenzli/carcass#1]
Is there a way to not force the frame around the license headers and footers? 

My typical header is:

```
(*
 * Copyright (c) 2013-2015 Thomas Gazagnaire <thomas@gazagnaire.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *)
```

I'm very happy to add the missing watermarking information (with `%%NAME%% %%VERSION%%)` but I'd like to avoid the arbitrary 77-columns filled by `-`at the beginning and end of the block of text.

**Comment by dbuenzli** [comment]
Just change the flesh and bones of your `~/.carcass` directory to your taste... But I'd really like to suggest that you keep the license at the end of the file like the default setup does, as a potential reader of your code I find it distateful that you bother me so much first with the legalese; that's usually not what I'm looking for.

**Comment by samoht** [comment]
But I don't seem to have control over the 
```
(*---------------------------------------------------------------------------
```
line (which is what I'm calling the frame).

I'm fine to put the legalese at the end, although I've pick ISC to have a less legalese as possible anyway.

**Comment by dbuenzli** [comment]
You have control over everything just edit `~/.carcass/ocaml/src`

**Comment by samoht** [comment]
My bad, I forgot to `grep -r` ... Thanks!
